### ISSUE TITLE
Hosted version of Open Custom GPT not working

### ISSUE THREAD

**Issue by Stoevne** [SamurAIGPT/Open-Custom-GPT#22] opened 2024-01-20 10:05 UTC
The 'Hosted version of Open Custom GPT' is not working.
When entering all the information (name, instructions, file,...) and clicking on "submit" nothing happens.
There is also no field to enter the OpenAI API.

**Comment by Anil-matcha** [comment] 2024-01-22 20:58
Can you try now, we have added fixes to show error messages. Let us know if you are still facing any issue

**Comment by Stoevne** [comment] 2024-01-23 16:21
Sorry, still nothing happens when hitting "Submit".

**Comment by Anil-matcha** [comment] 2024-01-23 19:50
<img width="1470" alt="akey2" src="https://github.com/SamurAIGPT/Open-Custom-GPT/assets/4326215/b6cd75d2-f6a9-4008-85eb-bda5e44320ca">

Have added a button now to click and change the OpenAI key directly as can be seen in this image. Please go ahead and set your openai key and it should then start working

**Comment by Anil-matcha** [comment] 2024-01-30 02:55
Closing as the issue is resolved

**Closed by Anil-matcha** 2024-01-30 02:55 UTC
